spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_employee
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
      '[hibernate.dialect]': org.hibernate.dialect.MySQL8Dialect
      
logging:
  level:
    '[org.hibernate.stat]': debug
    '[org.hibernate.type]': trace
    
server:
  port: 8082
         
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    refresh:
      enable: true
  instance:
    appname: ${spring.application.name}
